In [4]:
from iexfinance import get_historical_data 
from datetime import datetime

start = datetime(2017, 1, 1) # starting date: year-month-date
end = datetime(2018, 1, 1) # ending date: year-month-date

data = get_historical_data('SPY', start=start, end=end, output_format='pandas') 
data

                open      high       low     close     volume
date
2017-01-03  218.8967  219.6652  217.7720  219.0913   91366522
2017-01-04  219.4609  220.5600  219.4512  220.3947   78744433
2017-01-05  220.0931  220.3947  219.3247  220.2196   78379012
2017-01-06  220.3460  221.5327  219.7332  221.0075   71559922
2017-01-09  220.7157  220.8714  220.2354  220.2780   46939676
2017-01-10  220.2974  221.2409  219.8402  220.2780   63771939
2017-01-11  220.1807  220.9005  219.4317  220.9005   74650016
2017-01-12  220.3169  220.5600  218.8140  220.3460   72113181
2017-01-13  220.5406  221.1923  220.5017  220.8518   62717865
2017-01-17  220.1320  220.5892  219.6360  220.0737   61240814
2017-01-18  220.3509  220.6087  219.7332  220.5600   54793302
2017-01-19  220.6476  220.8032  219.2566  219.7430   66608787
2017-01-20  220.5114  221.1047  219.8032  220.5503  129168623
2017-01-23  220.1710  220.6135  219.1204  219.9764   75061645
2017-01-24  220.2196  221.8537  220.0931  221.3868   95555295
2017-01-25  222.4568  223.3031  222.2720  223.3031   84437712
2017-01-26  223.1377  223.4392  222.7583  223.0696   59970719
2017-01-27  223.1572  223.3225  222.5152  222.7194   59695224
2017-01-30  221.9413  221.9705  220.2293  221.3382   79737252
2017-01-31  220.7838  221.3868  220.1418  221.3187   75880805
2017-02-01  222.0240  222.3498  220.7449  221.4063   79117651
2017-02-02  220.9978  221.8732  220.6281  221.5522   69657560
2017-02-03  222.5735  223.2836  222.2234  223.0793   80563168
2017-02-06  222.6222  223.0657  222.3012  222.6805   57790108
2017-02-07  223.1182  223.3863  222.4763  222.6903   57931151
2017-02-08  222.3693  223.1280  222.0775  222.9821   51566218
2017-02-09  223.2933  224.6454  223.2544  224.3049   65955245
2017-02-10  224.6940  225.4430  224.3259  225.1901   66015892
2017-02-13  225.7445  226.7075  225.7154  226.4157   55182050
2017-02-14  226.2114  227.3300  225.8224  227.3203   71108983
...              ...       ...       ...       ...        ...
2017-11-16  254.0611  255.5607  254.0165  255.1463   67777027
2017-11-17  254.7517  255.1149  254.3077  254.3965   75756833
2017-11-20  254.6727  255.0526  254.3965  254.8306   48075514
2017-11-21  255.6988  256.7051  254.7938  256.4979   69176799
2017-11-22  256.5078  256.6557  256.0835  256.2710   45033392
2017-11-24  256.8235  256.9813  256.6656  256.8629   27856514
2017-11-27  256.9123  257.2477  256.5078  256.7347   52274922
2017-11-28  257.2576  259.3688  257.1540  259.3392   98971719
2017-11-29  259.4872  260.0890  258.6782  259.1814   77512102
2017-11-30  260.2173  262.4765  260.1285  261.4505  127894389
2017-12-01  261.2038  261.7464  257.2576  260.9079  164390902
2017-12-04  262.7330  263.2164  260.5330  260.5922   94040560
2017-12-05  260.8783  261.5886  259.5069  259.6549   77994544
2017-12-06  259.3392  260.1877  259.1814  259.7042   75898566
2017-12-07  259.5563  260.8783  259.4083  260.5231   77218569
2017-12-08  261.4307  261.9536  260.4851  261.9438   76563873
2017-12-11  262.0128  262.8021  261.9135  262.7330   83077533
2017-12-12  262.9895  263.7294  262.7675  263.1967   85195750
2017-12-13  263.4729  263.9662  263.0684  263.1671  102905409
2017-12-14  263.4927  263.6308  262.0325  262.0917  100666692
2017-12-15  263.2594  264.7864  263.1503  264.2609  144610290
2017-12-18  265.7978  266.3332  265.7185  265.9366   83653572
2017-12-19  266.2192  266.2638  264.8360  264.9153   82382876
2017-12-20  265.9961  266.0655  264.4394  264.7765   76751500
2017-12-21  265.4111  266.1201  265.0442  265.3218   67032339
2017-12-22  265.3516  265.3764  264.6476  265.2524   78720873
2017-12-26  264.7963  265.1807  264.6327  264.9351   45244433
2017-12-27  265.1235  265.4706  264.7567  265.0640   57750986
2017-12-28  265.6292  265.6590  265.1929  265.6094   45116139
2017-12-29  266.2638  266.2837  264.3898  264.6079   96007424

[251 rows x 5 columns]

In [5]:
import fix_yahoo_finance as yf
data = yf.download('SPY', '2018-01-01', '2018-08-22')

[*********************100%***********************]  1 of 1 downloaded

In [6]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-01-02,267.839996,268.809998,267.399994,268.769989,266.501160,86655700
2018-01-03,268.959991,270.640015,268.959991,270.470001,268.186829,90070400
2018-01-04,271.200012,272.160004,270.540009,271.609985,269.317169,80636400
2018-01-05,272.510010,273.559998,271.950012,273.420013,271.111938,83524000
2018-01-08,273.309998,274.100006,272.980011,273.920013,271.607727,57319200
2018-01-09,274.399994,275.250000,274.079987,274.540009,272.222473,57254000
2018-01-10,273.679993,274.420013,272.920013,274.119995,271.806000,69574300
2018-01-11,274.750000,276.119995,274.559998,276.119995,273.789093,62361500
2018-01-12,276.420013,278.109985,276.079987,277.920013,275.573944,90816100
2018-01-16,279.350006,280.089996,276.179993,276.970001,274.631958,106555100
2018-01-17,278.029999,280.049988,276.970001,279.609985,277.249634,109354500
2018-01-18,279.480011,279.959991,278.579987,279.140015,276.783630,100728000
2018-01-19,279.799988,280.410004,279.140015,280.410004,278.042908,140920100
2018-01-22,280.170013,282.690002,280.109985,282.690002,280.303650,91322400
2018-01-23,282.739990,283.619995,282.369995,283.290009,280.898590,97084700
2018-01-24,284.019989,284.700012,281.839996,283.179993,280.789520,134816100
2018-01-25,284.160004,284.269989,282.399994,283.299988,280.908508,84587300
2018-01-26,284.250000,286.630005,283.959991,286.579987,284.160797,107743100
2018-01-29,285.929993,286.429993,284.500000,284.679993,282.276825,90118300
2018-01-30,282.600006,284.739990,281.220001,281.760010,279.381500,131796400
2018-01-31,282.730011,283.299988,280.679993,281.899994,279.520325,108364800
2018-02-01,281.070007,283.059998,280.679993,281.579987,279.203003,90102500
2018-02-02,280.079987,280.230011,275.410004,275.450012,273.124786,173174800
2018-02-05,273.450012,275.850006,263.309998,263.929993,261.702026,294681800
2018-02-06,259.940002,269.700012,258.700012,269.130005,266.858124,355026800
2018-02-07,268.500000,272.359985,267.579987,267.670013,265.410461,167376100
2018-02-08,268.010010,268.170013,257.589996,257.630005,255.455215,246449500
2018-02-09,260.799988,263.609985,252.919998,261.500000,259.292542,283565300
2018-02-12,263.829987,267.010010,261.660004,265.339996,263.100098,143736000
2018-02-13,263.970001,266.619995,263.309998,266.000000,263.754547,81223600
...,...,...,...,...,...,...
2018-07-11,277.149994,278.040009,276.519989,276.859985,276.859985,77054700
2018-07-12,278.279999,279.429993,277.600006,279.369995,279.369995,60124700
2018-07-13,279.170013,279.929993,278.660004,279.589996,279.589996,48216000
2018-07-16,279.640015,279.799988,278.839996,279.339996,279.339996,48201000
2018-07-17,278.470001,280.910004,278.410004,280.470001,280.470001,52315500
2018-07-18,280.559998,281.179993,280.059998,281.059998,281.059998,44593500
2018-07-19,280.309998,280.739990,279.459991,280.000000,280.000000,61412100
2018-07-20,279.769989,280.480011,279.500000,279.679993,279.679993,82337700
2018-07-23,279.450012,280.429993,279.059998,280.200012,280.200012,47047600
2018-07-24,281.790009,282.559998,280.630005,281.609985,281.609985,68026900
2018-07-25,281.329987,284.369995,281.279999,284.010010,284.010010,78882900
2018-07-26,283.200012,284.109985,283.089996,283.339996,283.339996,57919500
2018-07-27,283.709991,283.820007,280.380005,281.420013,281.420013,76768700
2018-07-30,281.510010,281.690002,279.359985,279.950012,279.950012,63742500
2018-07-31,280.809998,282.019989,280.380005,281.329987,281.329987,68570500
2018-08-01,281.559998,282.130005,280.130005,280.859985,280.859985,53853300
2018-08-02,279.390015,282.579987,279.160004,282.390015,282.390015,63426400
2018-08-03,282.529999,283.660004,282.329987,283.600006,283.600006,53935400
2018-08-06,283.640015,284.989990,283.200012,284.640015,284.640015,39400900
2018-08-07,285.390015,286.010010,285.239990,285.579987,285.579987,43196600
2018-08-08,285.390015,285.910004,284.940002,285.459991,285.459991,42114600
2018-08-09,285.529999,285.970001,284.920013,285.070007,285.070007,35652400
2018-08-10,283.450012,284.059998,282.359985,283.160004,283.160004,77076000
2018-08-13,283.470001,284.160004,281.769989,282.100006,282.100006,65686900
2018-08-14,282.920013,284.170013,282.480011,283.899994,283.899994,43842000
2018-08-15,282.380005,282.540009,280.160004,281.779999,281.779999,102925400
2018-08-16,283.399994,285.040009,283.359985,284.059998,284.059998,69967900
2018-08-17,283.829987,285.559998,283.369995,285.059998,285.059998,65618500
2018-08-20,285.570007,285.970001,285.059998,285.670013,285.670013,39807500
2018-08-21,286.250000,287.309998,285.709991,286.339996,286.339996,66888000